language: ruby

services:
  - docker

jobs:
  include:
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64
  - os: linux
    arch: ppc64le
  - os: linux
    arch: s390x

before_install:
- docker build -t debian-adoptopenjdk .travis

script:
- docker run --mount type=bind,source="$(pwd)",target=/build debian-adoptopenjdk:latest "/build/.travis/docker-build.sh"

after_success:
- .travis/travis-after_success.sh