os: linux
dist: xenial

language: java

before_install:
  - sudo apt-get -y install apt-file
  - sudo apt-file update
  - sudo apt-file search libssl
  - sudo apt-get -y install libssl libssl-dev

jobs:
  include:
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12

install: mvn install
