language: java

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make
  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make

script:
  - ${MAKE} all
