language: java

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make
  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make

script:
  - ${MAKE} all
  - curl -T target/libopenssl4j* -usfuhrm:${BINTRAY_API_KEY} https://api.bintray.com/content/sfuhrm/openssl4j/objects/0.0.0/libopenssl4j-$(uname -m)-$(uname -s)-$(uname -r)
