os: linux
language: java

before_install:
  - sudo apt-get -y install apt-file
  - sudo apt-file update
  - sudo apt-file search libssl
  - sudo apt-get -y install libssl1.0.0 libssl-dev

jobs:
  include:
  - os: linux
    dist: xenial
    jdk: openjdk9
    env: SSLVERSION: 1.0.0
  - jdk: openjdk10
    dist: bionic
    env: SSLVERSION: 1.1.0
#  - jdk: openjdk11
#  - jdk: openjdk12

install:
  - sudo apt-get -y install apt-file
  - sudo apt-file update
  - sudo apt-file search libssl
  - sudo apt-get -y install libssl${SSLVERSION} libssl-dev
  - make install
  - mvn install
