language: java

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make
  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make

script:
  - ${MAKE} all

  
deploy:
  provider: bintray
  file: ".travis/bintray.json"
  user: "sfuhrm"
  key: "${BINTRAY_API_KEY}"
  skip_cleanup: true # to upload artifacts created during the build
