language: java

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make
  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - CC=gcc
      - MAKE=make

script:
  - ${MAKE} all

  
deploy:
  provider: bintray
  file: "Path to a descriptor file, containing information for the Bintray upload"
  user: "sfuhrm"
  key: "${BINTRAY_API_KEY}"
  passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
  skip_cleanup: true # to upload artifacts created during the build
