# This release process looks for tags and produces releases.
name: Release

on:
  push:
    tags:
      - 'openssl4j-parent-[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        body: |
          # Release ${{ steps.version.outputs.version }}
          ## Changes
          
          * 1
          * 2
          * 3

